globalThis.process ??= {}; globalThis.process.env ??= {};
import { e as createComponent, k as renderComponent, r as renderTemplate, u as unescapeHTML, m as maybeRenderHead } from '../../chunks/astro/server_C0THm8nM.mjs';
import { $ as $$Layout } from '../../chunks/Layout_BgZ1aDSE.mjs';
export { renderers } from '../../renderers.mjs';

var __freeze = Object.freeze;
var __defProp = Object.defineProperty;
var __template = (cooked, raw) => __freeze(__defProp(cooked, "raw", { value: __freeze(cooked.slice()) }));
var _a;
const prerender = false;
const $$Healthcare = createComponent(($$result, $$props, $$slots) => {
  const schema = { "@context": "https://schema.org", "@type": "WebPage", "name": "Sentinel for Healthcare", "description": "EU AI Act compliance for medical AI systems. MDR alignment, clinical decision support audit, patient safety AI oversight.", "url": "https://gettingsentinel.com/use-cases/healthcare", "publisher": { "@type": "Organization", "name": "Sentinel" } };
  return renderTemplate`${renderComponent($$result, "Layout", $$Layout, { "title": "Sentinel for Healthcare \u2014 EU AI Act & MDR AI Compliance", "description": "Deterministic AI audit trails for clinical decision support, diagnostic imaging AI, and patient risk scoring. EU AI Act and EU MDR compliance for healthcare providers." }, { "default": ($$result2) => renderTemplate(_a || (_a = __template([" ", '<header class="sticky top-9 z-50 border-b border-slate-900/80 backdrop-blur-xl bg-space/80"> <nav class="max-w-screen-xl mx-auto px-6 h-16 flex items-center justify-between"> <a href="/" class="flex items-center gap-2"><div class="w-7 h-7 rounded-lg bg-emerald-500 flex items-center justify-center text-space font-black text-sm">S</div><span class="font-bold text-sm text-white">SENTINEL</span></a> <div class="flex gap-3"><a href="/#pricing" class="btn-ghost !py-2 !px-4 !text-xs">View Plans</a><a href="/#pricing" class="btn-emerald !py-2 !px-4 !text-xs">Get Access</a></div> </nav> </header> <main class="max-w-screen-lg mx-auto px-6"> <section class="pt-28 pb-16 text-center"> <div class="text-5xl mb-6">\u{1F3E5}</div> <div class="section-label justify-center mb-4">INDUSTRY USE CASE \xB7 HEALTHCARE</div> <h1 class="text-4xl md:text-6xl text-white mb-6 tracking-tighter">EU AI Act Compliance<br><span style="color:var(--color-emerald);">for Healthcare</span></h1> <p class="text-slate-400 text-lg max-w-2xl mx-auto leading-relaxed">Medical AI systems are among the most strictly regulated under the EU AI Act. Diagnosis support, patient risk scoring, and clinical workflow AI all carry Article 6 High-Risk classifications. Sentinel generates the audit evidence required by both the AI Act and the EU Medical Device Regulation (MDR).</p> <div class="mt-8 flex flex-col sm:flex-row gap-4 justify-center"> <a href="https://radumuresanu.lemonsqueezy.com/checkout/buy/a4afd393-f642-41c7-ba71-bec3200ad514" class="lemonsqueezy-button btn-emerald">Deploy for Healthcare \u2014 $49/mo \u2192</a> <a href="/compliance" class="btn-ghost">Architecture Deep-Dive</a> </div> </section> <section class="py-16 border-t border-slate-900 grid md:grid-cols-2 gap-6"> ', ' </section> <section class="py-16 text-center border-t border-slate-900"> <h2 class="text-3xl text-white mb-6">Audit Your Clinical AI Today</h2> <a href="https://radumuresanu.lemonsqueezy.com/checkout/buy/a4afd393-f642-41c7-ba71-bec3200ad514" class="lemonsqueezy-button btn-emerald">Provision Sentinel for Healthcare \u2192</a> </section> </main> <footer class="border-t border-slate-900 py-8"><div class="max-w-screen-lg mx-auto px-6 flex justify-between items-center"><span class="mono text-xs text-slate-600">SENTINEL \xB7 HEALTHCARE USE CASE</span><a href="/" class="mono text-xs text-slate-600 hover:text-emerald-400 transition-colors">\u2190 Homepage</a></div></footer> <script type="application/ld+json">', "<\/script> "])), maybeRenderHead(), [
    { title: "Clinical Decision Support", art: "Annex III \xA75(a)", body: "Clinical decision support AI is listed in Annex III as a high-risk AI system. Sentinel provides structured audit logs per inference, enabling hospitals to demonstrate that AI recommendations were generated by a conforming system at every patient interaction." },
    { title: "Diagnostic Imaging AI", art: "Art. 12 + MDR", body: "Radiology and pathology AI must maintain decision traces under both the EU AI Act and MDR Annex IX. Sentinel's D1 schema captures image hash, model version, and verdict in a single write \u2014 below the latency threshold for real-time diagnostic workflows." },
    { title: "Patient Risk Stratification", art: "Art. 13 (Transparency)", body: "Patient-facing risk scores must be accompanied by an explanation of the factors that influenced them. Sentinel's compliance JSON provides a structured transparency artifact compliant with EHR audit requirements." },
    { title: "Hospital Resource Allocation AI", art: "Art. 14 (Human Oversight)", body: "AI systems making resource allocation decisions affecting patient care require demonstrable human oversight capability. Sentinel's webhook integration triggers your clinical governance team whenever an allocation AI verdict is flagged as non-compliant." }
  ].map((c) => renderTemplate`<div class="glass p-7 rounded-2xl"> <div class="mono text-[10px] text-emerald-400 tracking-widest uppercase mb-2">${c.art}</div> <h3 class="text-lg font-bold text-white mb-3">${c.title}</h3> <p class="text-slate-400 text-sm leading-relaxed">${c.body}</p> </div>`), unescapeHTML(JSON.stringify(schema))) })}`;
}, "D:/AI Act Compliance API/sentinel-landing/src/pages/use-cases/healthcare.astro", void 0);

const $$file = "D:/AI Act Compliance API/sentinel-landing/src/pages/use-cases/healthcare.astro";
const $$url = "/use-cases/healthcare";

const _page = /*#__PURE__*/Object.freeze(/*#__PURE__*/Object.defineProperty({
  __proto__: null,
  default: $$Healthcare,
  file: $$file,
  prerender,
  url: $$url
}, Symbol.toStringTag, { value: 'Module' }));

const page = () => _page;

export { page };
